### ISSUE TITLE
Redmine 5

### ISSUE THREAD

**Issue by sseypt** [jkraemer/stopwatch#10]
Hi there.

I'm running `sameersbn/redmine:5.0.0-1`, copied the files into `plugins/stopwatch` and getting this error on `docker compose restart`:

```
...
Migrating plugins. Please be patient, this could take a while...
rake aborted!
LoadError: cannot load such file -- stopwatch
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/home/redmine/redmine/plugins/stopwatch/init.rb:1:in `<top (required)>'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/home/redmine/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `catch'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:199:in `block in halting'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `each'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/reloader.rb:88:in `prepare!'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
/home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:367:in `require_environment!'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

Is this supposed to work with redmine 5 or am I doing something wrong?

Cheers,
Steve

**Comment by maressyl** [comment]
Hi,

Unfortunately even with Redmine version `5.0.4.stable` we run into problems after install when clicking the "Log time" button :

```
I, [2023-02-16T11:16:41.253926 #123019]  INFO -- : [8ba343d4-f237-4f97-a683-666ce3e43371] Started GET "/stopwatch_timers/new?project_id=" for 10.43.14.35 at 2023-02-16 11:16:41 +0100
I, [2023-02-16T11:16:41.255051 #123019]  INFO -- : [8ba343d4-f237-4f97-a683-666ce3e43371] Processing by StopwatchTimersController#new as JS
I, [2023-02-16T11:16:41.255104 #123019]  INFO -- : [8ba343d4-f237-4f97-a683-666ce3e43371]   Parameters: {"project_id"=>""}
I, [2023-02-16T11:16:41.260351 #123019]  INFO -- : [8ba343d4-f237-4f97-a683-666ce3e43371]   Current user: mareschalsy (id=34)
I, [2023-02-16T11:16:41.286302 #123019]  INFO -- : [8ba343d4-f237-4f97-a683-666ce3e43371] Completed 500 Internal Server Error in 31ms (ActiveRecord: 2.2ms | Allocations: 10024)
F, [2023-02-16T11:16:41.288034 #123019] FATAL -- : [8ba343d4-f237-4f97-a683-666ce3e43371]
[8ba343d4-f237-4f97-a683-666ce3e43371] NoMethodError (undefined method `running_time_entry_id' for #<User id: 34, login: ...>):
[8ba343d4-f237-4f97-a683-666ce3e43371]
[8ba343d4-f237-4f97-a683-666ce3e43371] plugins/stopwatch/app/controllers/stopwatch_timers_controller.rb:100:in `load_todays_entries'
[8ba343d4-f237-4f97-a683-666ce3e43371] plugins/stopwatch/app/controllers/stopwatch_timers_controller.rb:21:in `new'
[8ba343d4-f237-4f97-a683-666ce3e43371] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

The plugin's page advertises compatibility with "Redmine 4.2.x, 4.1.x, 4.0.x, 3.4.x.".

However we would also be very interested to have this very convenient plugin running in version 5 !

Best,
Sylvain

**Comment by calbasi** [comment]
I could participate in a financial support for the 5.x version, if needed.

**Comment by peldszus** [comment]
https://github.com/jkraemer/stopwatch/pull/9 solves this.

**Comment by jkraemer** [comment]
master now runs on Redmine 5.x
